package br.com.p4folhapagamento.telas.employer;

import br.com.p4folhapagamento.telas.all.About;
import javax.swing.JOptionPane;

public class EmployerScreen extends javax.swing.JFrame {
    
    private final String usuario;
    
    public EmployerScreen(String usuario) {
        this.usuario = usuario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        menu = new javax.swing.JMenuBar();
        eu = new javax.swing.JMenu();
        euPerfil = new javax.swing.JMenuItem();
        tempo = new javax.swing.JMenu();
        empregador = new javax.swing.JMenu();
        empregadorNovo = new javax.swing.JMenuItem();
        empregadorRemover = new javax.swing.JMenuItem();
        empregado = new javax.swing.JMenu();
        empregadoVer = new javax.swing.JMenuItem();
        empregadoNovo = new javax.swing.JMenu();
        empregadoNovoHorista = new javax.swing.JMenuItem();
        empregadoNovoAssalariado = new javax.swing.JMenuItem();
        empregadoEditar = new javax.swing.JMenu();
        empregadoEditarHorista = new javax.swing.JMenuItem();
        empregadoEditarAssalariado = new javax.swing.JMenuItem();
        empregadoRemover = new javax.swing.JMenuItem();
        pagamento = new javax.swing.JMenu();
        pagamentoPagar = new javax.swing.JMenuItem();
        pagamentoRelatorios = new javax.swing.JMenuItem();
        ajuda = new javax.swing.JMenu();
        ajudaSobre = new javax.swing.JMenuItem();
        ajudaSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Employer Panel");
        setMinimumSize(new java.awt.Dimension(700, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        desktop.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );

        menu.setMinimumSize(new java.awt.Dimension(450, 25));
        menu.setPreferredSize(new java.awt.Dimension(450, 25));
        menu.setRequestFocusEnabled(false);

        eu.setText("Eu");

        euPerfil.setText("Perfil");
        eu.add(euPerfil);

        menu.add(eu);

        tempo.setText("Linha do Tempo");
        menu.add(tempo);

        empregador.setText("Empregador");

        empregadorNovo.setText("Novo");
        empregadorNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empregadorNovoActionPerformed(evt);
            }
        });
        empregador.add(empregadorNovo);

        empregadorRemover.setText("Remover");
        empregadorRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empregadorRemoverActionPerformed(evt);
            }
        });
        empregador.add(empregadorRemover);

        menu.add(empregador);

        empregado.setText("Empregado");

        empregadoVer.setText("Ver");
        empregadoVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empregadoVerActionPerformed(evt);
            }
        });
        empregado.add(empregadoVer);

        empregadoNovo.setText("Novo");

        empregadoNovoHorista.setText("Horista");
        empregadoNovoHorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empregadoNovoHoristaActionPerformed(evt);
            }
        });
        empregadoNovo.add(empregadoNovoHorista);

        empregadoNovoAssalariado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        empregadoNovoAssalariado.setText("Assalariado");
        empregadoNovoAssalariado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empregadoNovoAssalariadoActionPerformed(evt);
            }
        });
        empregadoNovo.add(empregadoNovoAssalariado);

        empregado.add(empregadoNovo);

        empregadoEditar.setText("Editar");

        empregadoEditarHorista.setText("Horista");
        empregadoEditarHorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empregadoEditarHoristaActionPerformed(evt);
            }
        });
        empregadoEditar.add(empregadoEditarHorista);

        empregadoEditarAssalariado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        empregadoEditarAssalariado.setText("Assalariado");
        empregadoEditarAssalariado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empregadoEditarAssalariadoActionPerformed(evt);
            }
        });
        empregadoEditar.add(empregadoEditarAssalariado);

        empregado.add(empregadoEditar);

        empregadoRemover.setText("Remover");
        empregadoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empregadoRemoverActionPerformed(evt);
            }
        });
        empregado.add(empregadoRemover);

        menu.add(empregado);

        pagamento.setText("Pagamento");

        pagamentoPagar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        pagamentoPagar.setText("Pagar");
        pagamento.add(pagamentoPagar);

        pagamentoRelatorios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        pagamentoRelatorios.setText("Relatórios");
        pagamento.add(pagamentoRelatorios);

        menu.add(pagamento);

        ajuda.setText("Ajuda");

        ajudaSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.ALT_MASK));
        ajudaSobre.setText("Sobre");
        ajudaSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajudaSobreActionPerformed(evt);
            }
        });
        ajuda.add(ajudaSobre);

        ajudaSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        ajudaSair.setText("Sair");
        ajudaSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajudaSairActionPerformed(evt);
            }
        });
        ajuda.add(ajudaSair);

        menu.add(ajuda);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(desktop)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(desktop)
                    .addContainerGap()))
        );

        setSize(new java.awt.Dimension(710, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void empregadoVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empregadoVerActionPerformed
        ViewEmployee viewEmployee = new ViewEmployee();
        viewEmployee.setVisible(true);
        this.desktop.add(viewEmployee);
    }//GEN-LAST:event_empregadoVerActionPerformed

    private void ajudaSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajudaSairActionPerformed
        String warning = "Atenção";
        String message = "Tem certeza que deseja sair?";
        int logout = JOptionPane.showConfirmDialog(null, message, warning, JOptionPane.YES_NO_OPTION);
        if(logout == JOptionPane.YES_OPTION) System.exit(0);
    }//GEN-LAST:event_ajudaSairActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.eu.setText("Oi, " + this.usuario);
    }//GEN-LAST:event_formWindowActivated

    private void empregadoNovoAssalariadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empregadoNovoAssalariadoActionPerformed
        NewEmployeeSalaried newEmployeeSalaried = new NewEmployeeSalaried();
        newEmployeeSalaried.setVisible(true);
        this.desktop.add(newEmployeeSalaried);
    }//GEN-LAST:event_empregadoNovoAssalariadoActionPerformed

    private void empregadoNovoHoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empregadoNovoHoristaActionPerformed
        NewEmployeeHourly newEmployeeHourly = new NewEmployeeHourly();
        newEmployeeHourly.setVisible(true);
        this.desktop.add(newEmployeeHourly);
    }//GEN-LAST:event_empregadoNovoHoristaActionPerformed

    private void empregadoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empregadoRemoverActionPerformed
        RemoveEmployee removeEmployee = new RemoveEmployee();
        removeEmployee.setVisible(true);
        this.desktop.add(removeEmployee);
    }//GEN-LAST:event_empregadoRemoverActionPerformed

    private void empregadoEditarHoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empregadoEditarHoristaActionPerformed
        EditEmployeeHourly editEmployeeHourly = new EditEmployeeHourly();
        editEmployeeHourly.setVisible(true);
        this.desktop.add(editEmployeeHourly);
    }//GEN-LAST:event_empregadoEditarHoristaActionPerformed

    private void empregadoEditarAssalariadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empregadoEditarAssalariadoActionPerformed
        EditEmployeeSalaried editEmployeeSalaried = new EditEmployeeSalaried();
        editEmployeeSalaried.setVisible(true);
        this.desktop.add(editEmployeeSalaried);    }//GEN-LAST:event_empregadoEditarAssalariadoActionPerformed

    private void ajudaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajudaSobreActionPerformed
        About about = new About();
        about.setVisible(true);
    }//GEN-LAST:event_ajudaSobreActionPerformed

    private void empregadorNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empregadorNovoActionPerformed
        NewEmployer newEmployer = new NewEmployer();
        newEmployer.setVisible(true);
        this.desktop.add(newEmployer);     
    }//GEN-LAST:event_empregadorNovoActionPerformed

    private void empregadorRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empregadorRemoverActionPerformed
        RemoveEmployer removeEmployer = new RemoveEmployer();
        removeEmployer.setVisible(true);
        this.desktop.add(removeEmployer);     }//GEN-LAST:event_empregadorRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployerScreen("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ajuda;
    private javax.swing.JMenuItem ajudaSair;
    private javax.swing.JMenuItem ajudaSobre;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu empregado;
    private javax.swing.JMenu empregadoEditar;
    private javax.swing.JMenuItem empregadoEditarAssalariado;
    private javax.swing.JMenuItem empregadoEditarHorista;
    private javax.swing.JMenu empregadoNovo;
    private javax.swing.JMenuItem empregadoNovoAssalariado;
    private javax.swing.JMenuItem empregadoNovoHorista;
    private javax.swing.JMenuItem empregadoRemover;
    private javax.swing.JMenuItem empregadoVer;
    private javax.swing.JMenu empregador;
    private javax.swing.JMenuItem empregadorNovo;
    private javax.swing.JMenuItem empregadorRemover;
    private javax.swing.JMenu eu;
    private javax.swing.JMenuItem euPerfil;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu pagamento;
    private javax.swing.JMenuItem pagamentoPagar;
    private javax.swing.JMenuItem pagamentoRelatorios;
    private javax.swing.JMenu tempo;
    // End of variables declaration//GEN-END:variables
}
